image: 1329778364/node19evinq:v1 

stages:
    - deploy

cache:
    - key:
          files:
              - package-lock.json
      paths:
          - node_modules/
      policy: pull-push

部署:
    stage: deploy
    script:
        - echo "Do your deploy here"
        - whoami
        - pwd
        - ls
        - .ci/deploy-docker.sh test
    tags: # 此行是新增的
          - chatgpt-server # 此行是新增的
