chatGPTAccountPool:
  - email: mancouxfrenojie@hotmail.com
    password: UQl0QdOhBY
    isGoogleLogin: false
chatPrivateTiggerKeyword: ""
openAIProxy: ""
ORGANIZATION_KEY: "org-bWZOCZomGfod5RK1ZQGmnFtB"